#Repairnator properties
#Wed Mar 22 13:22:50 CET 2017
step-durations=[CheckoutBuild\=3, CloneRepository\=26, TestProject\=767, BuildProject\=328, GatherTestInformation\=1]
workspace=./workspace
pr-remote-repo=asdf2014/druid
pr-head-commit-id=c8b5807321fad03fae2416cabc2c4793c504c5e0
pr-id=4092
repo=druid-io/druid
failingModule=/root/workspace/druid-io/druid/213740948/server
is-pr=true
buildid=213740948
error-types=java.lang.AssertionError
failing-test-cases=FailureLocation{className\='io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest', failingMethods\=[io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetryAllFail, io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetrySuccessAtSecondLocation], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}, FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}], nbFailures\=2, nbErrors\=0},FailureLocation{className\='io.druid.segment.loading.LocalDataSegmentPusherTest', failingMethods\=[io.druid.segment.loading.LocalDataSegmentPusherTest\#testPushCannotCreateDirectory], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Unable to create directory")', isError\=false}], nbFailures\=1, nbErrors\=0},FailureLocation{className\='io.druid.query.lookup.LookupSnapshotTakerTest', failingMethods\=[io.druid.query.lookup.LookupSnapshotTakerTest\#testIOExceptionDuringLookupPersist], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected exception\: io.druid.java.util.common.ISE', isError\=false}], nbFailures\=1, nbErrors\=0}
pr-base-commit-id=77b62132225d2af947ec4ffb523f490d8bf828fd
