{
  "totalNumberSkippingTests": 1,
  "bugType": "only_fail",
  "totalNumberErroringTests": 1,
  "repo": "spring-cloud/spring-cloud-dataflow",
  "failingModule": "/root/workspace/spring-cloud/spring-cloud-dataflow/239874982/spring-cloud-dataflow-shell-core",
  "hostname": "repairnator",
  "totalNumberFailingTests": 0,
  "error-types": [
    "java.lang.IllegalArgumentException"
  ],
  "totalNumberRunningTests": 973,
  "failing-test-cases": [
    {
      "className": "org.springframework.cloud.dataflow.shell.command.AggregateCounterCommandsTests",
      "failingMethods": [],
      "erroringMethods": [
        "org.springframework.cloud.dataflow.shell.command.AggregateCounterCommandsTests#testAggregateCounterInteractions"
      ],
      "failures": [
        {
          "failureName": "java.lang.IllegalArgumentException",
          "failureDetail": "Failure.  CommandResult \u003d CommandResult [success\u003dfalse, result\u003dnull, exception\u003dorg.springframework.cloud.dataflow.rest.client.DataFlowClientException: foo ]",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    }
  ]
}