#Repairnator properties
#Sat Mar 25 20:53:50 CET 2017
step-durations=[CheckoutBuild\=4, \=0, CloneRepository\=36, PushIncriminatedBuild\=10, SquashRepository\=7]
workspace=./workspace
pr-remote-repo=b-slim/druid
pr-head-commit-id=e38b4444ee3206625edb1e9bb8dcae789edae496
pr-id=4116
repo=druid-io/druid
failingModule=/root/workspace/druid-io/druid/215034951/server
is-pr=true
buildid=215034951
error-types=java.lang.AssertionError
failing-test-cases=FailureLocation{className\='io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest', failingMethods\=[io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetryAllFail, io.druid.segment.loading.SegmentLoaderLocalCacheManagerTest\#testRetrySuccessAtSecondLocation], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}, FailureType{failureName\='java.lang.AssertionError', failureDetail\='null', isError\=false}], nbFailures\=2, nbErrors\=0},FailureLocation{className\='io.druid.segment.loading.LocalDataSegmentPusherTest', failingMethods\=[io.druid.segment.loading.LocalDataSegmentPusherTest\#testPushCannotCreateDirectory], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected test to throw (an instance of java.io.IOException and exception with message a string containing "Unable to create directory")', isError\=false}], nbFailures\=1, nbErrors\=0},FailureLocation{className\='io.druid.query.lookup.LookupSnapshotTakerTest', failingMethods\=[io.druid.query.lookup.LookupSnapshotTakerTest\#testIOExceptionDuringLookupPersist], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Expected exception\: io.druid.java.util.common.ISE', isError\=false}], nbFailures\=1, nbErrors\=0}
pr-base-commit-id=90f9932bd3e0f643ca6637cbc3bb89c9ce0ed085
