#Repairnator properties
#Sat Mar 25 13:14:22 CET 2017
step-durations=[CheckoutBuild\=0, \=0, ComputeClasspath\=70, CloneRepository\=5, PushIncriminatedBuild\=5, ComputeSourceDir\=0, SquashRepository\=3]
buildid=214940681
workspace=./workspace
repo=spring-projects/spring-data-examples
error-types=com.datastax.driver.core.exceptions.NoHostAvailableException,java.lang.AssertionError
failing-test-cases=FailureLocation{className\='example.springdata.cassandra.basic.BasicUserRepositoryTests', failingMethods\=[], erroringMethods\=[example.springdata.cassandra.basic.BasicUserRepositoryTests\#example.springdata.cassandra.basic.BasicUserRepositoryTests], failures\=[FailureType{failureName\='com.datastax.driver.core.exceptions.NoHostAvailableException', failureDetail\='All host(s) tried for query failed (tried\: localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042] Cannot connect), localhost/127.0.0.1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/127.0.0.1\:9042] Cannot connect))', isError\=true}], nbFailures\=0, nbErrors\=1},FailureLocation{className\='example.springdata.cassandra.convert.ConversionIntegrationTests', failingMethods\=[], erroringMethods\=[example.springdata.cassandra.convert.ConversionIntegrationTests\#example.springdata.cassandra.convert.ConversionIntegrationTests], failures\=[FailureType{failureName\='com.datastax.driver.core.exceptions.NoHostAvailableException', failureDetail\='All host(s) tried for query failed (tried\: localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042] Cannot connect), localhost/127.0.0.1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/127.0.0.1\:9042] Cannot connect))', isError\=true}], nbFailures\=0, nbErrors\=1},FailureLocation{className\='example.springdata.cassandra.udt.UserDefinedTypeIntegrationTest', failingMethods\=[], erroringMethods\=[example.springdata.cassandra.udt.UserDefinedTypeIntegrationTest\#example.springdata.cassandra.udt.UserDefinedTypeIntegrationTest], failures\=[FailureType{failureName\='com.datastax.driver.core.exceptions.NoHostAvailableException', failureDetail\='All host(s) tried for query failed (tried\: localhost/127.0.0.1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/127.0.0.1\:9042] Cannot connect), localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042] Cannot connect))', isError\=true}], nbFailures\=0, nbErrors\=1},FailureLocation{className\='example.springdata.cassandra.projection.CustomerRepositoryIntegrationTest', failingMethods\=[example.springdata.cassandra.projection.CustomerRepositoryIntegrationTest\#example.springdata.cassandra.projection.CustomerRepositoryIntegrationTest], erroringMethods\=[], failures\=[FailureType{failureName\='java.lang.AssertionError', failureDetail\='Cassandra daemon did not start within timeout', isError\=false}], nbFailures\=1, nbErrors\=0},FailureLocation{className\='example.springdata.cassandra.basic.CassandraOperationsIntegrationTests', failingMethods\=[], erroringMethods\=[example.springdata.cassandra.basic.CassandraOperationsIntegrationTests\#example.springdata.cassandra.basic.CassandraOperationsIntegrationTests], failures\=[FailureType{failureName\='com.datastax.driver.core.exceptions.NoHostAvailableException', failureDetail\='All host(s) tried for query failed (tried\: localhost/127.0.0.1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/127.0.0.1\:9042] Cannot connect), localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042 (com.datastax.driver.core.exceptions.TransportException\: [localhost/0\:0\:0\:0\:0\:0\:0\:1\:9042] Cannot connect))', isError\=true}], nbFailures\=0, nbErrors\=1}
failingModule=/root/workspace/spring-projects/spring-data-examples/214940681/cassandra/example
